### ISSUE TITLE
[Bug Report] User Details Breaks when Using this Theme

### ISSUE THREAD

**Issue by TearJoy** [CorellanStoma/CreArts#2]
Hi there! I know the theme is WIP but I figured I should mention this to get it out of the way.
It could be caused by the recent class names, but using CreArts breaks User Details, not in the sense that it actually breaks, but the actual "details" are not shown

Here is a preview of the user popout and profile modal with CreArts enabled:
![image](https://user-images.githubusercontent.com/81557214/121395206-b1530f80-c941-11eb-9084-e29dc7a7d6e1.png)
![image](https://user-images.githubusercontent.com/81557214/121395221-b617c380-c941-11eb-81a7-fc83a450bd0b.png)

and here is a preview of it disabled:
![image](https://user-images.githubusercontent.com/81557214/121395287-c7f96680-c941-11eb-9b95-b4b12a809082.png)
![image](https://user-images.githubusercontent.com/81557214/121395301-cb8ced80-c941-11eb-8257-dc238127de93.png)

Edit: I love this theme btw, super super clean. Looking forward to when it fully releases, and maybe next time when I find these issues I could just ping you in the powercord server, be sure to let me know.

**Comment by CorellanStoma** [comment]
Hi, thanks for the feedback! Currently I have deactivated the the user details plugin. As soon as discord is ready with the new user profile and Modal I will rework it together.

**Comment by CorellanStoma** [comment]
bug was fixed in v2.2.0
